sudo: true

install:
  - sudo apt-get update
  - sudo apt-get install curl
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install -y cabal-install-1.22 ghc-7.10.3
  - cat >> ~/.bashrc <<EOF
  - export PATH="$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH"
  - export PATH=~/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH
  - cabal update
  - curl -o racket.sh https://mirror.racket-lang.org/installers/6.5/racket-6.5-x86_64-linux.sh && echo 2 | sudo bash racket.sh

script:
  - cabal install alex
  - cabal install happy
  - cabal install
  - cabal configure
  - cabal build
  - /usr/racket/bin/racket tests/typechecker.rkt
  - /usr/racket/bin/racket tests/interpreter.rkt
