#!/bin/bash

set -x

stack build

if [[ -n $1 ]]; then
  tests="tests/${1}.rkt"
else
  tests="tests/core.rkt \
         tests/import-export.rkt \
         tests/scoping.rkt \
         tests/interpreter.rkt \
         tests/typechecker.rkt \
         tests/examples.rkt"
fi

raco="$(which raco)"
if [[ -z $raco ]]; then
  raco="/usr/racket/bin/raco"
fi

set -e
"$raco" test -t $tests
