#!/bin/bash

set -e

stack build

if [[ -n $1 ]]; then
  tests="tests/${1}.rkt"
else
  tests="tests/core.rkt tests/scoping.rkt tests/interpreter.rkt tests/typechecker.rkt tests/examples.rkt"
fi

raco test -t $tests
